# TODO CUSTOM: update footer social links to desired icons
extra:
  announcement:
    content: |
      <div class="promo-banner">
        <img src="assets/logo/png/logo_64.png" alt="Pufferfish" />
        <div>
          <strong>Pufferfish Platform</strong><br/>
          Современная экосистема для обработки сообщений и OCR-ответов.
        </div>
      </div>
  footer:
    content: ' '
    type: custom-bottom
  generator: Pufferfish Platform Docs
  meta:
  - content: Единая платформа для команд, которые строят масштабируемые сервисы ответа
      клиентам
    name: description
  - content: noindex, nofollow
    name: robots
  - content: microservices, Kafka, Telegram, VK, OCR, doc2text, pufferfish
    name: keywords
  - content: Pufferfish Platform
    property: og:title
  - content: Единая платформа для команд, которые строят масштабируемые сервисы ответа
      клиентам
    property: og:description
  - content: https://pufferfish-io.github.io/.github/assets/logo/png/logo_512.png
    property: og:image
  - content: https://pufferfish-io.github.io/.github/
    property: og:url
  - content: summary_large_image
    name: twitter:card
  - content: Pufferfish Platform
    name: twitter:title
  - content: Единая платформа для команд, которые строят масштабируемые сервисы ответа
      клиентам
    name: twitter:description
  - content: https://pufferfish-io.github.io/.github/assets/logo/png/logo_512.png
    name: twitter:image
  social:
  - icon: fontawesome/brands/github
    link: https://github.com/pufferfish-io
  - icon: fontawesome/brands/telegram
    link: https://t.me/pufferfish_io_bot
  - icon: fontawesome/brands/vk
    link: https://vk.com/pufferfishio
  - icon: material/briefcase
    link: https://hh.ru/resume/7ca1d8ecff0fad4d7d0039ed1f3339686c6d38
extra_css:
- assets/styles/custom.css
markdown_extensions:
- admonition
- toc:
    permalink: false
- def_list
- attr_list
nav:
- Главная: index.md
plugins:
- search
- include-markdown
site_author: Pufferfish.io team
site_description: Единая платформа для команд, которые строят масштабируемые сервисы
  ответа клиентам
site_name: Pufferfish Platform
site_url: https://pufferfish-io.github.io/.github
theme:
  favicon: assets/logo/favicon/favicon.ico
  features:
  - navigation.sections
  - navigation.expand
  - header.autohide
  hide:
  - feedback
  - footer
  language: ru
  logo: assets/logo/png/logo_256.png
  name: material
  palette:
  - accent: indigo
    primary: grey
    scheme: slate
