# TODO CUSTOM: update footer social links to desired icons
extra:
  generator: Pufferfish Platform Docs
  meta:
  - content: Единая платформа для команд, которые строят масштабируемые сервисы ответа
      клиентам
    name: description
  - content: microservices, Kafka, Telegram, VK, OCR, doc2text, pufferfish
    name: keywords
  - content: Pufferfish Platform
    property: og:title
  - content: Единая платформа для команд, которые строят масштабируемые сервисы ответа
      клиентам
    property: og:description
  - content: https://pufferfish-io.github.io/.github/assets/logo/pufferfish_logo.png
    property: og:image
  - content: https://pufferfish-io.github.io/.github/
    property: og:url
  - content: summary_large_image
    name: twitter:card
  - content: Pufferfish Platform
    name: twitter:title
  - content: Единая платформа для команд, которые строят масштабируемые сервисы ответа
      клиентам
    name: twitter:description
  - content: https://pufferfish-io.github.io/.github/assets/logo/pufferfish_logo.png
    name: twitter:image
  social:
  - icon: fontawesome/brands/github
    link: https://github.com/pufferfish-io
  - icon: fontawesome/brands/telegram
    link: https://t.me/pufferfish_io
  - icon: fontawesome/brands/vk
    link: https://vk.com/pufferfish_io
  - icon: material/web
    link: https://pufferfish-io.github.io/.github/
markdown_extensions:
- admonition
- toc:
    permalink: true
- def_list
- attr_list
nav:
- Обзор: index.md
plugins:
- search
- include-markdown
site_author: Pufferfish.io team
site_description: Единая платформа для команд, которые строят масштабируемые сервисы
  ответа клиентам
site_name: Pufferfish Platform
site_url: https://pufferfish-io.github.io/.github
theme:
  favicon: assets/logo/pufferfish_logo.png
  features:
  - navigation.tabs
  - navigation.sections
  - navigation.expand
  hide:
  - toc
  - feedback
  - footer
  language: ru
  logo: assets/logo/pufferfish_logo.png
  name: material
  palette:
  - accent: teal
    primary: indigo
    scheme: default
